version: '3.3'

services:

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
    restart: 'always'
    ports:
      - '5000:5000'
    environment:
      - FLASK_DEBUG=production